# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2

jobs:
  # Run default tests via tox test runner and submit code coverage information.
  testsuite:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: db
          POSTGRES_PASSWORD: dbpass

    environment: &testsuite_environment
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_HOST: localhost
      DJANGO_DB_NAME: db
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: dbpass

    steps:
      - checkout

      - restore_cache:
          keys:
            - virtualenv

      - run:
          name: Create virtualenv and install dependencies
          command: |
            python -m virtualenv -p $(which python3) ~/venv/
            source ~/venv/bin/activate
            pip install --upgrade tox codecov

      - save_cache:
          key: virtualenv
          paths:
            - "~/venv/"

      - run:
          name: "Run test suite"
          command: |
            source ~/venv/bin/activate
            tox

      - run:
          name: Submit code-coverage info
          command: |
            source ~/venv/bin/activate
            codecov

      - store_artifacts:
          path: build/htmlcov
          destination: coverage

      - store_artifacts:
          path: build/doc
          destination: doc

  # Build docker image and run the test suite within it
  test_image:
    machine: true

    environment:
      <<: *testsuite_environment

    steps:
      - checkout

      - run:
          name: Build container image
          command: |
            docker build \
              -t ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} \
              .

workflows:
  version: 2
  build_and_test:
    jobs:
      - testsuite
