# docker-compose file for local development and testing with container image.
version: '3.2'
services:
  db:
    image: postgres
    env_file:
      - base.env
    volumes:
      - postgres-data-local:/var/lib/postgresql/data
      - postgres-backup-local:/backups

  # Lookup proxy service
  lookupproxy:
    image: uisautomation/lookupproxy
    entrypoint: ["/tmp/wait-for-it.sh", "lookupproxy-db:5432", "--", "./manage.py", "runserver", "0.0.0.0:8080"]
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - "lookupproxy-db"
      - "lookupproxy-migration"
      - "hydra"
    volumes:
      - ./wait-for-it.sh:/tmp/wait-for-it.sh
      - ./lookupproxysettings.py:/usr/src/app/lookupproxysettings.py
    env_file:
      - lookupproxy.env
  lookupproxy-migration:
    image: uisautomation/lookupproxy
    depends_on:
      - "lookupproxy-db"
    volumes:
      - ./wait-for-it.sh:/tmp/wait-for-it.sh
      - ./lookupproxysettings.py:/usr/src/app/lookupproxysettings.py
    entrypoint: ["/tmp/wait-for-it.sh", "lookupproxy-db:5432", "--", "./manage.py", "migrate"]
    env_file:
      - lookupproxy.env
  lookupproxy-db:
    image: postgres
    env_file:
      - lookupproxy.env
    volumes:
      - lookupproxy-postgres-data-local:/var/lib/postgresql/data
      - lookupproxy-postgres-backup-local:/backups

  # Hydra OAuth2 infrastructure
  hydra:
    image: oryd/hydra:v0.11.6-alpine
    entrypoint: ["/tmp/start-hydra.sh"]
    ports:
      - "4444:4444"
      - "4445:4445"
    env_file:
      - hydra.env
    depends_on:
      - hydra-db
    volumes:
      - "./start-hydra.sh:/tmp/start-hydra.sh/:ro"
  hydra-consent:
    image: uisautomation/experimental-mock-consent-app
    env_file:
      - ./hydra-consent.env
    ports:
      - "8090:8090"
  # A service which waits for hydra to start and then creates the OAuth2
  # clients.
  hydra-create-clients:
    image: oryd/hydra:v0.11.6-alpine
    entrypoint: ["sh"]
    command: ["-c", "apk update && apk add bash && /tmp/create-oauth2-clients.sh"]
    env_file:
      - hydra.env
    depends_on:
      - hydra
    volumes:
      - "./wait-for-it.sh:/tmp/wait-for-it.sh/:ro"
      - "./create-oauth2-clients.sh:/tmp/create-oauth2-clients.sh/:ro"
  hydra-db:
    image: postgres
    env_file:
      - hydra.env
    volumes:
      - hydra-postgres-data-local:/var/lib/postgresql/data
      - hydra-postgres-backup-local:/backups


volumes:
  # Persistent volumes for postgres database data
  postgres-data-local:
  postgres-backup-local:
  lookupproxy-postgres-data-local:
  lookupproxy-postgres-backup-local:
  hydra-postgres-data-local:
  hydra-postgres-backup-local:
