# docker-compose file for local development and testing with container image.
#
# Extends compose/base.yml so launch services via:
#
#   docker-compose -f compose/base.yml -f compose/development.yml
version: '3.2'
services:
  # Web frontend
  frontend_app:
    build:
      context: ..
      dockerfile: ./compose/development.frontend.Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - "django_app"
    # For the frontend, mount the local frontend directory inside the container
    # as a volume to allow local changes to be reflected without having to
    # re-build the container.
    volumes:
      - type: bind
        source: ../frontend/
        target: /usr/src/app
        read_only: true

  # Main web application service
  django_app:
    build:
      context: ..
      dockerfile: ./compose/development.django.Dockerfile
    expose:
      - "8080"
    ports:
      - "8000:8080"
    depends_on:
      - "db"
      - "mailhog"
      - "hydra"
      - "lookupproxy"
    # For devserver, mount the local directory inside the container as a volume
    # to allow local changes to be reflected without having to re-build the
    # container.
    volumes:
      - type: bind
        source: ../
        target: /usr/src/app
        read_only: true
    environment:
      # Teleport JWPlatform credentials and configuration from host environment.
      JWPLATFORM_API_KEY: "${JWPLATFORM_API_KEY}"
      JWPLATFORM_API_SECRET: "${JWPLATFORM_API_SECRET}"
      JWPLATFORM_EMBED_PLAYER_KEY: "${JWPLATFORM_EMBED_PLAYER_KEY}"
    env_file:
      - base.env
      - development.env
