# Generated by Django 2.1 on 2018-08-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0007_update_arrayfield_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='allows_view_channel',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_permission', to='mediaplatform.Channel'),
        ),
    ]
