# Generated by Django 2.1 on 2018-08-06 13:49

from django.db import migrations, models


def ensure_channel_view_permission(apps, schema_editor):
    from mediaplatform import models as mpmodels
    # Query the ids of all channels which have a view permission.
    channels_with_view_permissions = (
        mpmodels.Permission.objects.filter(allows_view_channel__isnull=False)
        .values_list('allows_view_channel_id', flat=True)
    )
    # For channels which are *not* in the list above, create an empty view permission.
    mpmodels.Permission.objects.bulk_create([
        mpmodels.Permission(allows_view_channel=c)
        for c in mpmodels.Channel.objects.filter(~models.Q(id__in=channels_with_view_permissions))
    ])


def null_operation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mediaplatform', '0008_add_channel_view_permission'),
    ]

    operations = [
        # The reverse operation is null to stop Django complaining. It is OK for the channel view
        # permissions to continue to exist if this migration is rolled back.
        migrations.RunPython(ensure_channel_view_permission, null_operation),
    ]
